export const ELEMENTS = {
  nOfPeopleInput: '#ppl-in-household-input',
  zipCodeInput: '#zip-code-input',
  getStartedButton: '#get-started',
  invalidNum: '#invalidNum',
  invalidZipCode: '#invalidZipNum',
  invalidZip: '#invalidZip',
  defaultZip: '.default-zip',
  sectionName: '.sectionName',
  downloadButton: 'li > button',

  houseCarbonHeader: '.eps-header-info > h2',
  primaryHeatingSource: '#primaryHeatingSource',
  naturalGasTextInput: '#naturalGasTextInput',
  electricityTextInput: '#electricityTextInput',
  fuelTextInput: '#fuelTextInput',
  propaneTextInput: '#propaneTextInput',

  energyAC: '#energyAC',
  energyHeat: '#energyHeat',
  lightsToReplace: '#lightsToReplace',
  pwrMgmtSelect: '#pwrMgmtSelect',
  increaseGreenInput: '#increaseGreenInput',
  coldWaterSelect: '#coldWaterSelect',
  loadsPerWeek: '#loadsPerWeek',
  AirDrySelect: '#AirDrySelect',
  percentageAirDrySelect: '#percentageAirDrySelect',
  fridgeSelect: '#fridgeSelect',
  furnaceSelect: '#furnaceSelect',
  windowSelect: '#windowSelect',
  toTransportation: '#to-transportation',
  numVehiclesInput: '#numVehiclesInput',
  maintCurrentSelect: '#maintCurrentSelect',
  vehicle1Miles: '#vehicle1Miles',
  vehicle1Select: '#vehicle1Select',
  vehicle1GasMileage: '#vehicle1GasMileage',
  reduceMilesInput1: '#reduceMilesInput1',
  replaceVehicleInput1: '#replaceVehicleInput1',
  toWaste: '#waste',
  aluminumCheckbox: '#aluminumCheckbox',
  plasticCheckbox: '#plasticCheckbox',
  glassCheckbox: '#glassCheckbox',
  newspaperCheckboxR: '#newspaperCheckboxR',
  newspaperCheckboxR: '#newspaperCheckboxR',
  glassCheckboxR: '#glassCheckboxR',
  plasticCheckboxR: '#plasticCheckboxR',
  aluminumCheckboxR: '#aluminumCheckboxR',
  toReport: '#to-report',
  homeEnergyProgressBar: '#homeEnergyProgressBar',
  transportationProgressBar: '#transportationProgressBar',
  wasteProgressBar: '#wasteProgressBar',
  printicon: '#printicon',
  homeKey: '#homeKey',
  transKey: '#transKey',
  wasteKey: '#wasteKey',
  openSharePanel: '#openSharePanel',
  plannedActions: '#planned-actions > h2',
  gallons: '#plannedList > :nth-child(1) > div',
  trees: '#plannedList > :nth-child(3) > div',
  wast: '#plannedList > :nth-child(5) > div'
}